// US-07 (#12) — validation error codes. Names are used exactly as written in the issue.

export const ERROR_CODES = {
  MISSING_HEADER: 'MISSING_HEADER',
  RENAMED_HEADER: 'RENAMED_HEADER',
  UNKNOWN_HEADER: 'UNKNOWN_HEADER',
  EMPTY_FILE: 'EMPTY_FILE',
  NO_DATA_ROWS: 'NO_DATA_ROWS',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_NUMBER: 'INVALID_NUMBER',
  OUT_OF_RANGE: 'OUT_OF_RANGE',
  INVALID_DATE: 'INVALID_DATE',
  FUTURE_DATE: 'FUTURE_DATE',
  DUPLICATE_TUNNEL_DATE: 'DUPLICATE_TUNNEL_DATE',
  MALFORMED_COORDINATES: 'MALFORMED_COORDINATES',
  UNEXPECTED_ENUM_VALUE: 'UNEXPECTED_ENUM_VALUE',
  UNSURVEYED_ROW: 'UNSURVEYED_ROW',
}

// Codes that are recorded but do not fail the import.
export const WARNING_CODES = [
  ERROR_CODES.RENAMED_HEADER,
  ERROR_CODES.UNKNOWN_HEADER,
  ERROR_CODES.UNSURVEYED_ROW,
]
